CPP			    = g++
RM			    = rm -f
CPPFLAGS		= -Wall -I. -O2 -std=c++11 -g
LDFLAGS			= -lpthread -lzmqpp -lzmq -lsodium -Wl,--no-as-needed
SOURCES			= ../main_image.cpp ../image_analysis.cpp ../utils.cpp ../item.h ../robot_params.cpp ../messages.cpp ../../publisher.cpp ../../subscriber.cpp
TARGET			= main_image

all:	${TARGET}

clean:
	${RM} *.obj *~* ${TARGET}

${TARGET}:
	${CPP} ${CPPFLAGS} -o $@ $(SOURCES) ${LDFLAGS}


